### ISSUE TITLE
Any plan to update this blueprint?

### ISSUE THREAD

**Issue by Leowisd** [erkieh/generator-jhipster-react-mobx#6]
Hi Erki,

Hope all is well.

Do you have any plan to upgrade this blueprint to make it support JHipster version 7?

**Comment by erkieh** [comment]
Hi Yifu,
I am starting to update it now.

**Comment by erkieh** [comment]
Finally I have updated it

**Comment by zhx828** [comment]
@erkieh thanks for the update! I was trying to help upgrading to the recent 7.3.0 but my npm messes up everything, probably because of the version issue. I have not worked on the blueprint before, but would like to contribute to this project hoping to remove some pressure off you. Let me know how you think.

**Comment by erkieh** [comment]
@zhx828 Sure! Contributions are welcomed!
